---
create_user: ubuntu
ansible_user: root
ansible_ssh_host_key_checking: false
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/khang.toh@gmail.com/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw']